fix linux arm azure build
Co-authored-by: Cursor <cursoragent@cursor.com>

diff --git a/build-scripts/azure/ubuntu.yml b/build-scripts/azure/ubuntu.yml
--- a/build-scripts/azure/ubuntu.yml
+++ b/build-scripts/azure/ubuntu.yml
@@ -30,18 +30,44 @@ steps:
       cd "$(Build.SourcesDirectory)/FFmpeg"
       git apply ./build-scripts/configure-dav1d.patch
 
-      if [ "${{ parameters.ARCH }}" = "x86_64" ]; then
-        echo ./configure --enable-libdav1d  --enable-shared --disable-ffplay --disable-libxcb --disable-vulkan --disable-sdl2 --disable-xlib --enable-tvai --enable-libvpx --enable-libaom --enable-libzimg --enable-nvenc --enable-nvdec --extra-cflags="-I./conan/include -I./conan/include/videoai" --extra-ldflags="-Wl,-rpath,./conan/lib/ -L./conan/lib" --prefix=./output-conan/
-        set -e
-        ./configure --enable-libdav1d  --enable-shared --disable-ffplay --disable-libxcb --disable-vulkan --disable-sdl2 --disable-xlib --enable-tvai --enable-libvpx --enable-libaom --enable-libzimg --enable-nvenc --enable-nvdec --extra-cflags="-I./conan/include -I./conan/include/videoai" --extra-ldflags="-Wl,-rpath,./conan/lib/ -L./conan/lib" --prefix=./output-conan/
-      elif [ "${{ parameters.ARCH }}" = "armv8" ]; then
-        echo ./configure --enable-libdav1d  --enable-shared --disable-ffplay --disable-libxcb --disable-vulkan --disable-sdl2 --disable-xlib --enable-tvai --enable-libaom --enable-libzimg --enable-nvenc --enable-nvdec --extra-cflags="-I./conan/include -I./conan/include/videoai" --extra-ldflags="-Wl,-rpath,./conan/lib/ -L./conan/lib" --prefix=./output-conan/
-        set -e
-        ./configure --enable-libdav1d  --enable-shared --disable-ffplay --disable-libxcb --disable-vulkan --disable-sdl2 --disable-xlib --enable-tvai --enable-libaom --enable-libzimg --enable-nvenc --enable-nvdec --extra-cflags="-I./conan/include -I./conan/include/videoai" --extra-ldflags="-Wl,-rpath,./conan/lib/ -L./conan/lib" --prefix=./output-conan/
-      else
-        echo "Invalid ARCH: ${{ parameters.ARCH }}"
-        exit 1
-      fi
+      configure_flags=(
+        --enable-libdav1d
+        --enable-shared
+        --disable-ffplay
+        --disable-libxcb
+        --disable-vulkan
+        --disable-sdl2
+        --disable-xlib
+        --enable-tvai
+        --enable-libaom
+        --enable-libzimg
+        --enable-nvenc
+        --enable-nvdec
+        --extra-cflags="-I./conan/include -I./conan/include/videoai"
+        --extra-ldflags="-Wl,-rpath,./conan/lib/ -L./conan/lib"
+        --prefix=./output-conan/
+      )
+
+      case "${{ parameters.ARCH }}" in
+        x86_64)
+          configure_flags+=(--enable-libvpx)
+          ;;
+        armv8)
+          configure_flags+=(
+            --enable-cross-compile
+            --arch=aarch64
+            --target-os=linux
+            --cross-prefix=aarch64-linux-gnu-
+          )
+          ;;
+        *)
+          echo "Invalid ARCH: ${{ parameters.ARCH }}"
+          exit 1
+          ;;
+      esac
+
+      echo ./configure "${configure_flags[@]}"
+      ./configure "${configure_flags[@]}"
       
       make clean
       make -j$(nproc) install
